services: 
  nginx:
    image: nginx:1.21.5-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/dobie/nginx:/etc/nginx/conf.d
    container_name : nginx
    networks:
      - dobie

  backend:
    image: ko2sist/dobie-be:latest
    ports:
      - 8010:8080
    volumes:
      - /var/dobie/data:/data
      - /var/dobie/nginx:/nginx
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: dobie-be
    depends_on:
      - nginx
    networks:
      - dobie

  frontend:
    image: ko2sist/dobie-fe:latest
    ports:
      - 3333:80
    container_name: dobie-fe
    depends_on:
      - nginx
      - backend
    networks:
      - dobie


networks:
  dobie:
    external: true